### ISSUE TITLE
No sound on SNES emulator in Retro-Go 1.31.1, but sound works on the other emulators

### ISSUE THREAD

**Issue by ryan-makes-it** [ducalex/retro-go#11]
I just received a MRGC G32 ESP32 Retro Gaming Console, and installed Retro-Go 1.31.1 for the SNES emulator.  However, I have no sound from the several SNES games I have tried (F-Zero, Castlevania - Dracula X, Super Mario World, etc).  The NES emulator plays sound just fine.

I have tried changing the "Audio out" option from "Ext DAC" to "Dummy", but that doesn't seem to be helping.  

I'm happy to share debugging logs or whatever else you need - thanks for creating this lovely software package!

**Comment by smutek110** [comment]
Snes doesn't have sound support yet. 
Check in the description.

**Comment by ryan-makes-it** [comment]
Ah, my apologies, I missed that - thank you!

**Comment by ducalex** [comment]
I will add a popup to say "SNES is very slow and has no sound" when using it for the first time. I understand that not everybody reads the README :) .

**Comment by ryan-makes-it** [comment]
Yea, I apparently stoped at the "Nintendo: NES, Gameboy, Gameboy Color, SNES (very slow)" in the README.md :-/ 

The SNES emulation did not feel slow to me - at least not in F-Zero, which is the game I've played the most.  Maybe in a more demanding game it would feel slower?

In any case, thanks for updating me so quickly about this, and thanks for putting this together.  Now I'm going to be hauling a Game Boy-ish device everywhere with me again...
