### ISSUE TITLE
Overclock

### ISSUE THREAD

**Issue by Seannor** [ducalex/retro-go#154]
Hello! Is overclock settings under debug menu for info only, or it actually should change cpu speed? I tried several values, and didn't see any difference in GBC games. And values always rollback to 240mhz, after exiting game. Odroid-Go, fw 1.43.

**Comment by Seannor** [comment]
Hmm. Is it possible to make in future firmwares, make setting stay before device os toggled off? It should be safe enough.
Maybe even 80mhz enough for mario)

BTW, frameskip fully automatic or it could be configured? Can't find that setting.
PS. FPS counter ingame would be sweet, if it not difficult. Sorry for digression from main topic.

**Comment by ducalex** [comment]
> Is it possible to make in future firmwares, make setting stay before device os toggled off? It should be safe enough.
Maybe even 80mhz enough for mario)

80Mhz 160Mhz 240Mhz are indeed safe, it's frequencies over that that are considered overclocked. But what would be the benefit of running at 80Mhz? Marginally less power used?

> BTW, frameskip fully automatic or it could be configured? Can't find that setting.

Frameskip is automatic and cannot be configured in the UI. In almost all emulators (including GBC) it ends up being a fixed 0 or 1.

**Comment by Seannor** [comment]
> Marginally less power used?
Difference so little? I thought it could squeeze a couple of hours for addition gaming.

**Comment by ducalex** [comment]
I did some test many years ago and the difference between 80Mhz and 240Mhz was about 10-15mA (from the USB side).

The ODROID-GO usually use about 110-120mA (from the USB side). So I guess a ~10% improvement might be possible?

But at 80Mhz we'd have to disable other things like partial updates and that would increase our SPI/LCD power usage.

So in the end it doesn't seem worth it to me. 

But if you run proper tests and present convincing numbers I would reconsider, reducing power usage is always nice!
