### ISSUE TITLE
let me out of recovery mode!!!!!

### ISSUE THREAD

**Issue by SSStarku** [ducalex/retro-go#163]
When I connect my esp32 s3 to my ili9341 I only see the recovery mode

[config.h.txt](https://github.com/user-attachments/files/17547655/config.h.txt)

**Comment by ducalex** [comment]
Recovery mode is entered by holding a button during boot, the serial output will tell you which one. #define RG_RECOVERY_BTN to 0 if you want to prevent recovery but you clearly have an input problem and it will interfere with normal usage too.

**Comment by SSStarku** [comment]
thanks i will change it
-another question, what is it for?

**Comment by SSStarku** [comment]
thanks for the information :)
