### ISSUE TITLE
Need Help: Failed to read device's partition table!

### ISSUE THREAD

**Issue by 32teeth** [ducalex/retro-go#17]
**Describe the bug**

This is when attempting to flash onto a clean chip. Seems something is wrong with partition table

```
A fatal error occurred: Invalid head of packet (0x20)
An exception: ** Command '['/opt/homebrew/opt/python@3.9/bin/python3.9', '/Users/32teeth/esp/esp-idf-4.1/components/esptool_py/esptool/esptool.py', '--port', '/dev/cu.usbserial-110', '--baud', '2000000', 'read_flash', '32768', '3072', '/var/folders/vt/9b_057w16zbg29qggcndmfh40000gn/T/tmpaq1ryxuk']' returned non-zero exit status 2. ** occurred in _call_esptool.
Failed to read device's partition table!
```

**To Reproduce**

* `$PORT` and `$BAUD` are in my ENV
* all apps built

```
python rg_tool.py --target retro-esp32 --port $PORT --baud $BAUD flash all
```

**Local Fix**
If i revert the `rg_tools.py` to this [commit](https://github.com/ducalex/retro-go/commit/b5a2956a14a4e107c04eda502e8b63cb8d96761f) i can run the above command with an `--offset`

```
python rg_tool.py --port $PORT --baud $BAUD flash all --offset=0x80000
```

**Comment by ducalex** [comment]
If it's a clean chip then you must [follow this](https://github.com/ducalex/retro-go#installation=) to do the initial retro-go installation. Subsequently the `flash` command will work as expected. That is true for the older --offset method as well.

But it's not clear to me from your log if it's a partition table error or a serial error. If it's the latter then maybe baudrate is problematic? Can you try a much lower baudrate like 115200 just to see if it works?

**Comment by 32teeth** [comment]
> If it's a clean chip then you must [follow this](https://github.com/ducalex/retro-go#installation=) to do the initial retro-go installation.

What i did
* Erase flash `erase_flash`
* Erase storage `erase_region`
* Run `python rg_tool.py --port $PORT --baud $BAUD flash all`

Still produces the above error, interesting thing is that i can flash the launcher and any emulator as a single item using
* `idf.py build`
* `idf.py -p $PORT -b $BAUD flash`

I will try again in the morning and review the `rg_tools.py` file
