### ISSUE TITLE
Game&Watch Games roms converting guide

### ISSUE THREAD

**Issue by KD-MM2** [ducalex/retro-go#43]
Finally I was made the G&W games running. You should add this link as a guide to make the games to work with G&W Emulator
https://gist.github.com/DNA64/16fed499d6bd4664b78b4c0a9638e4ef

EDIT: I converted some roms for testing, you can find it [here](https://drive.google.com/drive/folders/1OiRe6UPNw1xvs9jYDQeXyyySApcGQZ9u?usp=sharing)

**Comment by ducalex** [comment]
I've added a link to your gist and to the lcd-game-shrinker to the readme!

And thanks for the ROMs, I will use them for testing myself, but I don't think I can link to them? What's the copyright status on these games?
