### ISSUE TITLE
compile error in prboom

### ISSUE THREAD

**Issue by mikeinkl1** [ducalex/retro-go#45]
had to comment this line out in "doomdef.h" to get the latest release to compile:

#define exit(x) rg_system_switch_app(RG_APP_LAUNCHER, RG_APP_LAUNCHER, 0, 0);

then it compiles OK but it crashes when exiting doom.

**Comment by ducalex** [comment]
What was the compile error?

**Comment by mikeinkl1** [comment]
`../components/prboom/doomdef.h:47:72:` error: expected declaration specifiers or '...' before numeric constant
 #define exit(x) rg_system_switch_app(RG_APP_LAUNCHER, RG_APP_LAUNCHER, 0, 0);``

**Comment by mikeinkl1** [comment]
I tried compiling the dev branch but it hangs before it even gets to doom.
`/retrogo/retro-go-dev/components/retro-go/rg_utils.c:119:15:` error: implicit declaration of function 'realloc' [-Werror=implicit-function-declaration]
    strings = realloc(strings, (strings_count + 1) * sizeof(char*));``

**Comment by ducalex** [comment]
It's probably just missing an `#include <stdlib.h>` at the top of rg_utils.c, try adding it (I will push that fix myself later today too).

Which version of esp-idf and OS are you using? Because I wonder why there's so much differences between your setup and mine.

**Comment by mikeinkl1** [comment]
I'm using a ubuntu VM and  ESP-IDF v4.1.3-129-g7c0f5e658e-dirty

**Comment by ducalex** [comment]
Thanks for the info!
