### ISSUE TITLE
How to build a mrgc fw

### ISSUE THREAD

**Issue by mrkellyhuang** [ducalex/retro-go#47]
Sorry ,this is not a bug.
I want to build mrgc F/W myself. 
I have cloned the project and configured the esp_idf 4.3.  
After running " ./rg_tool.py build-fw" , I got the file :"retro-go_1.35.1-dirty_odroid-go.fw", but it is not  for ESPGBC. 
Which config file should I modify to build the mrgc F/W.
Thank you.

**Comment by KD-MM2** [comment]
You need to change the build target here:
https://github.com/ducalex/retro-go/blob/master/rg_tool.py#L20

**Comment by mrkellyhuang** [comment]
Thank you for your reply. I will read these two documents carefully. I think I can solve it now. Thank you.

**Comment by ducalex** [comment]
Just to clarify, there is also a flag for rg_tool.py, there is no need to edit its source: `./rg_tool.py --target=mrgc-g32 build-fw`

There is also an environment variable that can be used to define the default target instead: `RG_TOOL_TARGET=mrgc-g32`.

**Comment by mrkellyhuang** [comment]
thank you Alex, thanks for your coding and improvement.
