### ISSUE TITLE
"GAME & WATCH" crashed

### ISSUE THREAD

**Issue by smutek110** [ducalex/retro-go#61]
"GAME & WATCH" where to get roms with * .GW extension. Everywhere it finds only the extension * .MGW

**Comment by ducalex** [comment]
You need to use this tool to pack MAME roms https://github.com/bzhxx/LCD-Game-Shrinker. I don't know if you can find already made .gw online and I can't really share them with you due to copyright...

**Comment by smutek110** [comment]
Thank You .
