### ISSUE TITLE
GBC - Pokemon Trading Card Game 1 and 2 fail to run

### ISSUE THREAD

**Issue by Cralex** [ducalex/retro-go#65]
**Describe the bug**
On 1.35.1, I can't get Pokemon Trading Card Game (CRC32 81069D53) and Pokemon Trading Card Game 2 English Patched (CRC32 D880DFC1) to run. If starting from a new game, both boot to a black screen, without locking up the system or triggering a crash. If starting from a previous save state, they'll run until the game needs to load something and then softlock. This happens on both the public release on OdroidGo and on my Game Box Mini port in development.

**Comment by Cralex** [comment]
Worth noting that my development environment matches the code at the time of the last release, so any later changes to the GBC emulator isn't reflected in my copy of the Game Box Mini firmware.

**Comment by ducalex** [comment]
What is the last retro-go version you remember working correctly with this game? (if any)

**Comment by Cralex** [comment]
I'll try some old versions and get back to you. They definitely worked before, since I have some save preview images of the games running properly.

**Comment by ducalex** [comment]
Thanks for tracking down the exact versions! Fixed in 76a4be91ad186a341acd59e1f3acb17667728c63.
