### ISSUE TITLE
Not connecting to WiFi

### ISSUE THREAD

**Issue by jobitjoseph** [ducalex/retro-go#67]
**Describe the bug**
Not connecting to WiFi. Created the wifi.json file and added the wifi SSID and password, But not connecting WiFi.
Device ESP32 wrover 16Mb
**To Reproduce**
1. Created the wifi.json file
2. added the wifi SSID and password
3. But not connecting WiFi. In system menu network status not configured

**Comment by mikeinkl1** [comment]
Did you compile it with wifi enabled?

**Comment by ducalex** [comment]
It's been almost two years with no response, I'm going to assume that your problem has been fixed or that you've moved to another project.

Feel free to re-open this issue if you need further help.
