### ISSUE TITLE
Launcher - Incorrect Date Displayed in UI

### ISSUE THREAD

**Issue by Cralex** [ducalex/retro-go#74]
**Describe the bug**
Some time ago, I noticed that both of my Retro-Go devices were showing a date of December 14th in the about section of the menu. Connecting to WiFi sets the time as normal, (at least, in the status bar) but the date isn't updating. I finally got around to looking in the web file browser, and the correct date seems to be appearing there.

Both pictures taken within minutes of each other.

**Screenshots**
![image](https://user-images.githubusercontent.com/1504649/209525777-905061cd-89f2-49a3-9bd5-e8fa3b6f824e.jpeg)

![image](https://user-images.githubusercontent.com/1504649/209525795-73f1134e-8b9a-4b0a-9ff6-9e0de8d7f6ed.jpeg)

**Comment by ddrsoul** [comment]
I can't check right now, but I believe that this is date when firmware was create.

**Comment by Cralex** [comment]
Oh, that explains it. I am looking in the "about" section after all.
