### ISSUE TITLE
Unused var

### ISSUE THREAD

**Issue by 32teeth** [ducalex/retro-go#84]
**Describe the bug**
> Less of a bug, more of a chore

Running a build command with `--without-netowkring`
Produces
```
warning: 'SETTING_WIFI_SLOT' defined but not used [-Wunused-variable]
 static const char *SETTING_WIFI_SLOT = "slot";
```

**Comment by ducalex** [comment]
Should be fixed in bcff7c14370756634fc598e3076f816978704c93. Feel free to re-open or submit a PR if you find more warnings!
